// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListApi.Models;

namespace ToDoListApi.Migrations
{
    [DbContext(typeof(ToDoListApiContext))]
    partial class ToDoListApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoListApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Career Goals"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Life Goals"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Yolo Goals"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Friendship"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Garden"
                        });
                });

            modelBuilder.Entity("ToDoListApi.Models.CategoryItem", b =>
                {
                    b.Property<int>("CategoryItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("ItemId");

                    b.HasKey("CategoryItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("CategoryItem");

                    b.HasData(
                        new
                        {
                            CategoryItemId = 1,
                            CategoryId = 2,
                            ItemId = 1
                        },
                        new
                        {
                            CategoryItemId = 2,
                            CategoryId = 3,
                            ItemId = 2
                        },
                        new
                        {
                            CategoryItemId = 3,
                            CategoryId = 5,
                            ItemId = 5
                        },
                        new
                        {
                            CategoryItemId = 4,
                            CategoryId = 4,
                            ItemId = 3
                        },
                        new
                        {
                            CategoryItemId = 5,
                            CategoryId = 1,
                            ItemId = 4
                        });
                });

            modelBuilder.Entity("ToDoListApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Priority");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Walk the doog",
                            Priority = 0
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Pet the cat",
                            Priority = 0
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Water the plants",
                            Priority = 0
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Ask for help",
                            Priority = 0
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "meditate",
                            Priority = 0
                        });
                });

            modelBuilder.Entity("ToDoListApi.Models.CategoryItem", b =>
                {
                    b.HasOne("ToDoListApi.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoListApi.Models.Item", "Item")
                        .WithMany("Categories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
